// DATA FOR YARNS AND PALETTES ////////////////////////

// YARNS //////////////////////////////////////////////

// yarn list, build as you go below
yarns = [];

// ----------------------------------------------------
// Default syllables title match

let Default = {
  name: "Default",
  magic: ['3','4','2','3','4','3','0','0','0','0','0','0','0'],
  colors: ["#f09f20","#fbd489","#3c6a96","#63a26f","#c1bae3",
           "#535e74","#ffffff","#ffffff","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff"],
  clusters: 47 // also good: 29
};
yarns.push(Default);

// ----------------------------------------------------
// Impeccable - Falling Leaves Varigated - I hook - moss

let ImpLeaves = {
  name: "Impeccable Leaves",
  magic: ['3','4','7','3','0','0','0','0','0','0','0','0','0'],
  colors: ["#853E37","#FFCE2E","#DE921F","#A61E27","#ffffff",
           "#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff"],
  clusters: 25
};
yarns.push(ImpLeaves);

// ----------------------------------------------------
// Red Heart Super Saver Pooling - Berry - I hook - moss

let RHPBerry = {
  name: "Red Heart Berry",
  magic: ['3','3','3','3','3','3','0','0','0','0','0','0','0'],
  colors: ["#663366","#eeeeee","#ff99cc","#cc6699","#cc3399",
           "#993366","#ffffff","#ffffff","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff",],
  clusters: 26
};
yarns.push(RHPBerry);

// ----------------------------------------------------
// Red Heart Super Saver Pooling - Berry - I hook - moss with fat 2's
// white = pull up, pull thru 1st, pull up, pull thru all 3 on hook

let RHPBerry2 = {
  name: "Red Heart Berry alt",
  magic: ['3','2','3','3','3','3','0','0','0','0','0','0','0'],
  colors: ["#663366","#eeeeee","#ff99cc","#cc6699","#cc3399",
           "#993366","#ffffff","#ffffff","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff"],
  clusters: 26
};
yarns.push(RHPBerry2);

// ----------------------------------------------------
// Red Heart Super Saver Pooling - Shaded Dusk

let RHShadedDusk = {
  name: "Red Heart Shaded Dusk",
  magic: ['5','10','4','0','0','0','0','0','0','0','0','0','0'],
  colors: ["#a8e9ff","#1028a2","#3156c4","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff"],
  clusters: 28
};
yarns.push(RHShadedDusk);

// ----------------------------------------------------
// Blue Barn Fiber Arts - Hand-dyed Dead Man's Hand
// mostly palindromic pattern

let BlueBarnHand = {
  name: "Blue Barn Dead Man's Hand",
  magic: ['1','3','4','3','2','3','3','4','0','0','0','0','0'],
  colors: ["#f5f5f5","#E5AD3A","#858585","#E5AD3A","#f5f5f5",
           "#E5AD3A","#858585","#E5AD3A","#ffffff","#ffffff",
           "#ffffff","#ffffff","#ffffff"],
  clusters: 17
};
yarns.push(BlueBarnHand);

// ----------------------------------------------------
// Impeccable - Luxury Ombre - G hook - moss

// let ImpLuxury = {
//   name: "Impeccable Luxury",
//   magic: ['3','3','#E5AD3A'3','4','0','0','0','0','0','0','0'],
//   colors: ["#33cccc","#333399","#9999ff","#333399","#33cccc",
//            "#cc99ff","#ffffff","#ffffff","#ffffff","#ffffff",
//            "#ffffff","#ffffff","#ffffff"],
//   clusters: 49
// }
// yarns.push(ImpLuxury);



// COLOR PALETTES /////////////////////////////////////

// these are color palettes generated by chat-gpt
  
palettes = [
  ["#3D5A80", "#98C1D9", "#A0C7C9", "#EE6C4D", "#293241"], 
  ["#4B4E6D", "#6B7AA1", "#8CBEB2", "#ECEEAB", "#F9A875", "#F08E5E"], 
  ["#F1D1B5", "#E8B7B7", "#D97171", "#574240"], 
  ["#90AFC5", "#336B87", "#2A3132", "#763626", "#DCAE1D"],
  ["#D3E2C3", "#A3C68C", "#287D73", "#1C313A"],
  ["#EF476F", "#FFD166", "#06D6A0", "#118AB2"], 
  ["#0B3C49", "#1E5059", "#007880", "#8FCCBE"],
  ["#B6D8F2", "#7EAED3", "#FFC400", "#FF8100", "#F04100"], 
  ["#FFC947", "#FF593B", "#8B2635", "#004E64"], 
  ["#E6EBE0", "#BBB6DF", "#6B70B2", "#3B3B98"], 
  ["#B7CBBF", "#1D4E89", "#6D9DC5", "#F2D3A9"], 
  ["#DE9E48", "#DBAE85", "#AA988D", "#645A5A"], 
  ["#354F52", "#4A6C6F", "#FA7F72", "#FFC85B", "#F5E356"], 
  ["#FDF1CC", "#F4D35E", "#EE964B", "#F95738", "#D45079"],
  ["#D9D9D9", "#8C8C8C", "#5D5D5D", "#333333"], 
  ["#C5E1A5", "#AED581", "#9CCC65", "#689F38"], 
  ["#FFCDB2", "#FFB4A2", "#E5989B", "#B5838D"], 
  ["#d0F8EA", "#A8DADC", "#457B9D", "#1D3557"], 
  ["#5E503F", "#6B5B95", "#8B81C3", "#E6AF2E"], 
  ["#E0E1E2", "#2E2F2F", "#6B717E", "#D7C3C3"], 
  ["#F0CDB4", "#EB8A90", "#654236", "#432818"], 
  ["#3E3B4F", "#F15F79", "#7C83FD", "#8EA7FF"], 
  ["#5B5B5B", "#8E8E8E", "#BDBDBD", "#FFFAFA"], 
  ["#FE938C", "#E6B89C", "#EAD2AC", "#9CAFB7"], 
  ["#FFB085", "#FFA2D9", "#9B4A97", "#76448A"], 
  ["#F3D0CD", "#CBBEB5", "#8C8279", "#51574F"], 
  ["#EF476F", "#FFD166", "#06D6A0", "#118AB2"], 
  ["#d7ddd7", "#8EF9F3", "#4C7C6D", "#1E1F26"],
  ["#F5A962", "#E8A87C", "#E6D4A7", "#4E4B3A"], 
  ["#F4E0E6", "#CE6D8B", "#B1476B", "#4B3F72"], 
  ["#dAd7F2", "#E8D7A5", "#393D3F", "#2A2C2B"], 
  ["#ccF5DB", "#90C290", "#44891A", "#263627"], 
  ["#e63946", "#f1faee", "#a8dadc", "#457b9d", "#1d3557"], 
  ["#ffadad", "#ffd6a5", "#F1F2D2", "#caffbf", "#9bf6ff", "#a0c4ff", "#bdb2ff", "#ffc6ff"], 
  ["#264653", "#2a9d8f", "#e9c46a", "#f4a261", "#e76f51"], 
  ["#006d77", "#83c5be", "#DDEEF4", "#ffddd2", "#e29578"], 
  ["#e5e5e5", "#8e9aaf", "#e0ece4", "#a3c4bc", "#16262e", "#3a4e48"], 
  ["#c9cdc9", "#f3b61f", "#ce796b", "#c18c5d", "#1b1d1e"], 
  ["#f94144", "#f3722c", "#f8961e", "#f9c74f", "#90be6d", "#43aa8b", "#577590"], 
  ["#d8f3dc", "#b7e4c7", "#95d5b2", "#74c69d", "#52b788", "#40916c", "#2d6a4f"], 
  ["#1b4332", "#2d6a4f", "#40916c", "#52b788", "#74c69d", "#95d5b2", "#b7e4c7", "#d8f3dc"], 
  ["#c7ccc7", "#1a535c", "#ff6b81"], 
  ["#ffe066", "#119da4", "#19647e", "#1c1c1c"], 
  ["#f8e9a1", "#f76c6c", "#a8d0e6", "#374785", "#24305e"],
  ["#ef476f", "#ffd166", "#06d6a0", "#118ab2", "#073b4c", "#606c38", "#283618"], 
  ["#f1ca8c", "#a1c181", "#619b8a", "#5a4b6a", "#e85d75", "#d00000", "#9d0208", "#6a040f"], 
  ["#1a202c", "#2d3748", "#4a5568", "#718096", "#a0aec0", "#cbd5e0", "#f2e8c0", "#edf2f7", "#f7fafc", "#cecece"], 
  ["#e07a5f", "#3d405b", "#81b29a", "#f2cc8f", "#d8a47f", "#bc6c25", "#4a4e4d", "#0f4c5c", "#10375c", "#ff5400"], 
  ["#ff9f1c", "#ffb30f", "#ff006e", "#cbf3f0", "#2ec4b6", "#0a9396", "#542e71", "#ff595e", "#ffca3a", "#8ac926", "#1982c4"], 
  ["#283d3b", "#197278", "#edddd4", "#c44536", "#772e25", "#dda15e", "#f5cb5c", "#242423", "#2b2d42", "#8d99ae", "#edc2c4", "#ef233c"], 
  ["#ff9f00", "#ff5200", "#ff006c", "#a30000", "#5f0000", "#aacc00", "#78a32c", "#0c8346", "#0b3d91", "#6f69c1", "#dd6fd9", "#f26df9", "#cecece"], 
  ["#ffebf0", "#ffc2d2", "#ff99b5", "#ff7097", "#ff4780", "#ff1f68", "#e60050", "#cc0040", "#b2002c", "#990019", "#800000", "#660000", "#4c0000"], 
  ["#d9e4ff", "#bac8ff", "#9bacff", "#7a90ff", "#5975ff", "#3859ff", "#174dff", "#003fff", "#0033cc", "#002999", "#001f66", "#001533", "#000a00"], 
  ["#ccf5cc", "#C4D9C4", "#b3e6b3", "#99d699", "#80c780", "#66b766", "#4da64d", "#339933", "#198c19", "#007f00", "#006600", "#004c00", "#003300"], 
  ["#ffe6d9", "#ffccb3", "#ffb28d", "#ff9968", "#ff8042", "#ff661c", "#e64d00", "#cc3f00", "#b23200", "#992600", "#801a00", "#661100", "#4c0800"], 
  ["#e0ccff", "#d1b3ff", "#c299ff", "#b380ff", "#a366ff", "#944dff", "#8533ff", "#751aff", "#6600ff", "#5900e6", "#4c00cc", "#3f00b2", "#320099"], 
  ["#1a1a1a", "#2e2e2e", "#424242", "#565656", "#727272", "#878787", "#979797", "#a8a8a8", "#bcbcbc", "#c7c7c7", "#d7d7d7", "#e1e1e1", "#eeeedde"], 
  ["#a7d7c5", "#f7f2e7", "#c7eae4", "#b2e2d9", "#86a192", "#5e6d5d"], 
  ["#d9ac7c", "#d6c8b1", "#b1a18c", "#8d756d", "#6a594f", "#443c32"], 
  ["#ffb3ba", "#ffdfba", "#ffffba", "#baffc9", "#bae1ff", "#f2a2e4"], 
  ["#ff7f7f", "#ffc1c1", "#ffd9d9", "#ffecec", "#aa6e6e", "#995757"], 
  ["#8e9a3b", "#a7b84e", "#c4d761", "#e1f573", "#7c8541", "#58652d"], 
  ["#2b2d42", "#4e5166", "#6a7d89", "#8ba5ac", "#abd1c6", "#d1f1e0"],
  ["#bdd9bf", "#c9ebd8", "#d9f7f1", "#f0fff8", "#9ec2b8", "#709687"], 
  ["#2c3e50", "#34495e", "#7f8c8d", "#95a5a6", "#bdc3c7", "#e0e0e0"],
  ["#6c5b7b", "#c06c84", "#f67280", "#f8b195"],
  ["#e63946", "#f1faee", "#a8dadc", "#457b9d", "#1d3557", "#e76f51", "#f9c74f"],
  ["#2a363b", "#e84a5f", "#ff847c", "#feceab", "#99b898", "#355c7d"],
  ["#e5fcc2", "#9de0ad", "#45ada8", "#547980", "#594f3b", "#f7cac9", "#92a8d1"],
  ["#f8b195", "#f67280", "#c06c84", "#6c5b7b", "#355c7d", "#99b898", "#e9d9d3"],
  ["#cdd180", "#f7bb97", "#e6717c", "#c84c61", "#34445c", "#4d4d4d", "#000"],
  ["#1b4332", "#40916c", "#52b788", "#74c69d", "#99d98c", "#caeac9", "#e9edc9"],
  ["#9c89b8", "#f0a6ca", "#efc3e6", "#f0e6ef", "#b8bedd", "#62b6cb"],
  ["#5c5c5c", "#ff9933", "#333333", "#cccccc"],
  ["#8d9b6a", "#404b3f", "#CFB4B4", "#e7e7e7"],
  ["#284b5a", "#b02e2e", "#f4bc60", "#ffffff"],
  ["#4e4d4a", "#e06651", "#2f5d62", "#baad63"],
  ["#4b4b4b", "#ffffff", "#3b3b3b", "#ffcc00", "#ff6600"],
  ["#e0c5c0", "#cec2c2", "#a5d5d0", "#9eb7b0", "#d6e3dd"],
  ["#e6bccd", "#f3b6c0", "#f9d9a8", "#c3e0dc", "#b7d5e5"],
  ["#d8f3dc", "#bde0fe", "#ffc9b6", "#e2cfea", "#9fd8df"],
  ["#f7d6e0", "#f5efef", "#d5f8eb", "#aee1e1", "#b8b5ff"],
  ["#d2e2dc", "#9ac2c9", "#e6a0c4", "#efb7e3", "#fee1e8"],
  ["#ffd7ba", "#ffe5d9", "#d6f5f5", "#c0e1ff", "#cfb7db"],
  ["#9e6649", "#d1986a", "#e6b582", "#f2d3a7", "#9c9f84", "#6f8196"],
  ["#6b5a5a", "#8f5e5e", "#b38080", "#d9a8a8", "#e7c6c6", "#f0e0e0"],
  ["#7e6b3e", "#9f8f64", "#bfae88", "#dfcdac", "#8b7b6c", "#bea794"],
  ["#7e5432", "#af7450", "#e0966f", "#f1b78f", "#7d5432", "#af724a"],
  ["#a8744c", "#c99563", "#e7b579", "#f4cc8e", "#9e875c", "#7e6b3e"],
  ["#997867", "#bb8f7a", "#ddbfae", "#ede4d9", "#8a7b6c", "#e7c6c6"],
  ["#7d6756", "#a08d7f", "#c3b2a9", "#e6d7d3", "#5b5e5c", "#777a78"],
  ["#9e6649", "#d1986a", "#e6b582", "#f2d3a7", "#9c9f84", "#6f8196"],
  ["#3c3b3f", "#67697c", "#8a93a5", "#b5bfce", "#e0e5e9", "#b29c85"],
  ["#4d3e3e", "#7b6a69", "#a99697", "#d8c2c5", "#a67250", "#d8a27e"],
  ["#36454f", "#798086", "#abb0b6", "#e1e5ea"],
  ["#2f2e34", "#5a5a5e", "#8e8e92", "#c7c7cc"],
  ["#3b3d47", "#6e707b", "#a2a5b5", "#d5d7e1"],
  ["#6f9eaf", "#84b59f", "#a3cc83", "#e8dda8"],
  ["#34656d", "#57a99a", "#a8dbb7", "#f4e4c7"],
  ["#2f4858", "#61a9a6", "#b2dbbf", "#fceeb5"],
  ["#266150", "#4d8b70", "#74b49b", "#a9e1bc"],
  ["#474747", "#81a3a7", "#b4c7ab", "#f6e5aa"],
  ["#3a506b", "#5c73a8", "#a67ebf", "#ee6c81"],
  ["#2c7da7", "#59a5d8", "#a0d0e0", "#f2e9e4", "#f9d29d", "#ffa766"],
  ["#688b8a", "#a9c0c0", "#f4dada", "#f4b6b6", "#b4a9a9", "#866c6a"],
  ["#006466", "#065a60", "#0c4c5f", "#6a919b", "#9db5c1", "#d0e1e1"],
  ["#d1b280", "#e6ce9f", "#e9d8be", "#d3e7e1", "#a6cfd5", "#84b6b2"],
  ["#0a2239", "#186384", "#5f8daa", "#c0e5e5", "#B7B7F8", "#efb7b7"],
  ["#4b3f72", "#846c92", "#b4a4b9", "#e0d1d1", "#e9bcb7", "#f5a28b"],
  ["#50514f", "#627f8c", "#83a598", "#bcbabe", "#f4f4f4", "#f25f5c"],
  ["#0b132b", "#1c2541", "#3a506b", "#5bc0be", "#ECD5D5", "#a2d5c6"],
  ["#c4507e", "#f3b3bb", "#fde6e6", "#9e9d92"],
  ["#fdd835", "#82a6b1", "#ffa12c", "#95d2c8"],
  ["#84a9ac", "#c3dfd9", "#e8eceb", "#7c7877", "#b2797f", "#f4b5c4"],
  ["#4a4e69", "#9a8c98", "#c9ada7", "#f2e9e4", "#e07a5f", "#3d405b"],
  ["#a06cd5", "#c5b9e9", "#ede9f8", "#f5d5c0", "#f1b24a"],
  ["#a3de83", "#f7e8aa", "#d7c49e", "#bfb7a4", "#8b9f9e", "#4a4c4b"],
  ["#f7d6e0", "#c3a1d9", "#7d84b2", "#3d3b3c", "#b9d9eb", "#a8a8a8", "#f7f5e6"],
  ["#4a708b", "#87a1b2", "#c4d4e0", "#5e6f88"],
  ["#5a95a9", "#ace1af", "#E2EACA", "#d6dccf", "#a8b6a0"],
  ["#7dce94", "#c2eabd", "#EDF2E4", "#a9a491", "#69664c"],
  ["#a7c5eb", "#c8dfeb", "#E3DBDB", "#f3d2c1", "#e9ac99"],
  ["#00909e", "#5dbcd2", "#a2d4ab", "#f5e5a4", "#ee964b"],
  ["#4b6a4d", "#88a55e", "#c1d682", "#e8edc9", "#9d9f94"],
  ["#6a8e7a", "#a7cbaa", "#d7e7d0", "#f7f7f7", "#7b9ea8", "#c2d2e2"],
  ["#e07a5f", "#3d405b", "#81b29a", "#f2cc8f", "#e9c46a", "#f4a261", "#2a9d8f"],
  ["#69a2b0", "#acc9ce", "#e1e7e7"],
  ["#34495e", "#678db2", "#a0c1dd", "#dde7f2"],
  ["#8e5572", "#c083a1", "#e6a9c9", "#ffe2e9", "#9d9d93"],
  ["#007f7f", "#52b2b2", "#a8e6e6", "#eaf7f7", "#0b3d91", "#3a6fcd"],
  ["#4a4e6d", "#8e92ab", "#ced1d6", "#f5f5f5", "#e5c5b5", "#c69963", "#a0522d"],
  ["#b1a7a6", "#d5c0a1", "#f2e2d2", "#b6c2b6", "#81a68d", "#54696d", "#3c3c3c"],
  ["#9e579d", "#c49ec6", "#e6d3e8", "#a2d2ff", "#1695a3", "#1a659e", "#0e2f56"],
  ["#225560", "#4b7e8f", "#8ab6c1", "#f4eade", "#d2b48c", "#9f6934", "#6e4226", "#3b271e"],
  ["#eef5db", "#86af49", "#649f43", "#3d6f31", "#6d3d6a", "#974e91", "#cda4de", "#ffe6ff", "#ffd7b5", "#ffa756"],
  ["#2e8bc0", "#48a9a6", "#c4dfe6", "#d4f1f4"],
  ["#ff8c69", "#ffa270", "#ffb997", "#ffd1c1"], 
  ["#9b5de5", "#c77dff", "#e4b1fc", "#f0e6ff"], 
  ["#5e60ce", "#3b3d99", "#8980f5", "#a5a5f5"],
  ["#5e5ea1", "#6db7b6", "#a2e1e1", "#ddf2f2"], 
  ["#ff7f50", "#ff9e80", "#ffb3a3", "#ffd6cc"], 
  ["#af69c8", "#cc85d4", "#e4b2df", "#f8e6f1"], 
  ["#6a529e", "#856fd6", "#a6a0e6", "#e6e1f6"], 
  ["#007ea7", "#5abdb0", "#a5d5d8", "#e5f5f5"], 
  ["#ff6b81", "#ff8da1", "#ffafc0", "#ffe0e0"] 
];



